# prism theme for fuzzel
# paste into fuzzel.ini, or keep as a file and add under [main]:  include=~/.config/fuzzel/prism-fuzzel.ini

[colors]

background=000000ff
text=bda7f0ff

prompt=ff7447ff
input=ff7447ff
match=ff7447ff

selection=ff7447ff
selection-text=000000ff
selection-match=000000ff

border=bda7f0ff
placeholder=989898ff
